version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DYNACONF_MLFLOW__TRACKING_URI=http://mlflow:5000
    volumes:
      - mlflow_data:/app/mlruns
    depends_on:
      - mlflow
    restart: unless-stopped

  mlflow:
    image: python:3.11-slim
    command: >
      bash -c "pip install mlflow psycopg2-binary &&
              mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:///mlflow"
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    restart: unless-stopped

volumes:
  mlflow_data:
