version: '3.8'

services:

  nginx:
    image: mlops.azurecr.io/nginx:latest
    ports:
      - "80:80"

  mlflow:
    image: mlops.azurecr.io/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    restart: unless-stopped


  backend:
    image: mlops.azurecr.io/backend:latest
    ports:
      - "8080:8080"
    environment:
      - DYNACONF_MLFLOW__TRACKING_URI=http://mlflow:5000
    volumes:
      - mlflow_data:/app/mlruns
    depends_on:
      - mlflow
    restart: unless-stopped

  frontend:
    image: mlops.azurecr.io/frontend:latest
    ports:
      - "8501:8501"
    environment:
      - DYNACONF_BACKEND_URL=http://backend:8080/predict
    depends_on:
      - backend
    restart: unless-stopped

  docs:
    image: mlops.azurecr.io/docs:latest
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  mlflow_data:
