version: '3.8'

services:

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5000"
    volumes:
      - mlflow_data:/mlflow
    restart: unless-stopped


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DYNACONF_MLFLOW__TRACKING_URI=http://mlflow:5000
    volumes:
      - mlflow_data:/app/mlruns
    depends_on:
      - mlflow
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - DYNACONF_BACKEND_URL=http://backend:8080/predict
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mlflow_data:
