default:
  mlflow:
    tracking_uri: mlruns
    experiment_name: AdultIncome
  optimization:
    n_trials: 10
  models:
    - XGBClassifier
    - RandomForestClassifier
  dataset:
    path: notebooks/data/adult.csv
    origin_path: notebooks/data/adult_origin.csv
    columns:
      target: income
      features:
        - age
        - educational-num
        - capital-gain
        - capital-loss
        - hours-per-week
        - workclass
        - education
        - marital-status
        - occupation
        - relationship
        - race
        - gender
        - native-country
        - fnlwgt
