[project]
name = "docs"
version = "0.1.0"
requires-python = ">=3.11"
description = "MLOps Project Docs"
dependencies = [
    "sphinx==8.1.0",
    "myst-parser==4.0.1",
    "sphinx-rtd-theme==3.0.2",
    "jupyter==1.1.1",
    "nbsphinx==0.9.7",
    "pandoc==2.4",
]
