[project]
name = "frontend"
version = "0.1.0"
requires-python = ">=3.11"
description = "MLOps Project Docs"
dependencies = [
    "sphinx==8.2.3",
    "myst-parser==4.0.1",
    "sphinx-rtd-theme==3.0.2",
]
