name: Build and Deploy
on:
  push:
    branches:
        - main

jobs:
    test-backend:
        runs-on: ubuntu-latest
        steps:
        -   name: Install Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'
        -   name: Checkout Code
            uses: actions/checkout@v4

        -   name: Install dependencies
            run: python -m pip install .['dev']
            working-directory: backend

        -   name: Run tests
            run: pytest || exit 1
            working-directory: backend
            env:
                PYTHONPATH: ${{ github.workspace }}/backend


    test-docker-backend-build:
        needs: test-backend
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Build Docker image
                run: docker build -t mlops-backend .
                working-directory: backend

            -   name: Run Docker container
                run: docker run -d -p 8080:80 --name mlops-backend mlops-backend
                working-directory: backend

            -   name: Check if container is running
                run: docker ps | grep mlops-backend
                working-directory: backend

            -   name: Stop Docker container
                run: docker stop mlops-backend
                working-directory: backend

    # TODO: Test frondend

    deploy:
        runs-on: ubuntu-latest
        needs: test-docker-backend-build
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Deploy to production
                run: echo "Deploying to production"q
