name: Build and Push to ACR
on:
  workflow_run:
    workflows: ["Pytest"]
    branches: [main]
    types: [completed]

env:
  REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to Azure Container Registry
      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest

      - name: Build and Push MLflow
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.mlflow
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/mlflow:latest

      - name: Build and Push Docs
        uses: docker/build-push-action@v5
        with:
          context: ./docs
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/docs:latest

      - name: Build and Push Nginx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.nginx
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx:latest
