name: Build and Test Backend Docker Image
on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
    test-docker-backend-build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Build Docker image
            run: docker build -t mlops-backend .
            working-directory: backend

          - name: Run Docker container
            run: docker run -d -p 8080:8080 --name mlops-backend mlops-backend
            working-directory: backend

          - name: Wait for container health check
            timeout-minutes: 10  # Increased timeout to 10 minutes
            run: |
              echo "Waiting for API to be ready..."
              # More robust health check with better error handling
              attempts=0
              max_attempts=60
              while [ $attempts -lt $max_attempts ]; do
                health_status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/health || echo "failed")

                if [ "$health_status" = "200" ]; then
                  echo "Health check succeeded after $attempts attempts!"
                  break
                fi

                # Show progress indicator and logs every 30 seconds
                if [ $((attempts % 10)) -eq 0 ]; then
                  echo "Still waiting... (Attempt $attempts of $max_attempts)"
                  echo "Container logs so far:"
                  docker logs mlops-backend --tail 20
                fi

                attempts=$((attempts+1))
                sleep 10  # Check every 10 seconds
              done

              if [ $attempts -eq $max_attempts ]; then
                echo "Health check timed out after $max_attempts attempts"
                docker logs mlops-backend
                exit 1
              fi

          - name: Stop Docker container
            if: always()
            run: |
              docker stop mlops-backend
              docker rm mlops-backend
