name: Docker
on:
  pull_request:
    branches:
      - main

jobs:
    test-docker-backend-build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Build Docker image
            run: docker build -t mlops-backend .
            working-directory: backend

          - name: Run Docker container
            run: docker run -d -p 8080:80 --name mlops-backend mlops-backend
            working-directory: backend

          - name: Wait for container health check
            timeout-minutes: 1
            run: |
              while ! curl -s http://localhost:8080/health > /dev/null; do
                sleep 1
              done

          - name: Check health and API endpoints
            run: |
              # Health check
              health_response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/health)
              if [ $health_response -ne 200 ]; then
                echo "Health check failed with status code $health_response"
                docker logs mlops-backend
                exit 1
              fi

              # Log container status
              echo "Container logs:"
              docker logs mlops-backend

          - name: Stop Docker container
            if: always()
            run: |
              docker stop mlops-backend
              docker rm mlops-backend
