name: Pytest
on:
  push:
    branches-ignore:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: python -m pip install .['dev']
        working-directory: backend

      - name: Run tests
        run: pytest || exit 1
        working-directory: backend
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
